# GC from OCaml

all: subsetphp_gc.o

subsetphp_gc.o: subsetphp_gc.c
	gcc -c -o subsetphp_gc.o -I byterun/caml -I byterun byterun/*.o subsetphp_gc.c -lm -ldl -lncurses

subsetphp_gc.a:
	ar rcs subsetphp_gc.a byterun/*.o 
